# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_room', models.CharField(max_length=200)),
                ('course_schedule', models.DateTimeField()),
                ('course_duration', models.DurationField()),
                ('course_seats', models.DecimalField(decimal_places=5, max_digits=5)),
                ('course_gender', models.CharField(max_length=200)),
                ('course_grade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='guardian_obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_id', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_middlename', models.CharField(max_length=200)),
                ('guardian_lastname', models.CharField(max_length=200)),
                ('guardian_2ndlastname', models.CharField(max_length=200)),
                ('guardian_phone', models.CharField(max_length=8)),
                ('guardian_relation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='profesor_obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor_id', models.CharField(max_length=200)),
                ('profesor_name', models.CharField(max_length=200)),
                ('profesor_lastname', models.CharField(max_length=200)),
                ('profesor_phone', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='student_obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('student_middlename', models.CharField(max_length=200)),
                ('student_lastname', models.CharField(max_length=200)),
                ('student_2ndlastname', models.CharField(max_length=200)),
                ('student_birthday', models.DateTimeField()),
                ('student_grade', models.CharField(max_length=200)),
                ('student_gender', models.CharField(max_length=200)),
                ('student_phone', models.CharField(max_length=8)),
                ('student_address', models.TextField(max_length=800)),
                ('student_guardian', models.ManyToManyField(to='LiftingEnkiMatriculas.guardian_obj')),
            ],
        ),
        migrations.AddField(
            model_name='course_obj',
            name='course_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LiftingEnkiMatriculas.profesor_obj'),
        ),
    ]
